steps:
  - label: ":go: :test_tube: Test"
    command: go test -v ./...
    parallelism: 5
    key: test
    plugins:
      - docker#v5.12.0:
          image: "golang:1.24.2" 
  - label: ":female-construction-worker: Build"
    command: go build -o /sandbox .
    depends_on: "test"
    plugins:
      - docker#v5.12.0:
          image: golang:1.24.2